spring:
  application:
    name: cljz-blog
  datasource:
    url: jdbc:mysql://192.168.1.103:3306/audio-visual?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 192.168.1.103
    password: 123456
server:
    port: 2020
