spring:
  application:
    name: cljz-blog
  datasource:
    url: jdbc:mysql://本地数据库地址:3306/audio-visual?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: 数据库账号
    password: 数据库密码
  jpa:
    show-sql: true
  redis:
    port: 6379
    host: 地址
    password: 密码
server:
    port: 2020
